//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Test.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Roles = new HashSet<Role>();
        }
    
        public int UserId { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string UserLogin { get; set; }
        public string Pswd { get; set; }
        public string EmailId { get; set; }
        public bool IsApproved { get; set; }
        public string PswdQuestion { get; set; }
        public string PswdAnswer { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public bool IsLockedOut { get; set; }
        public Nullable<System.DateTime> LockedOutDate { get; set; }
        public int FailedLoginAttemptCount { get; set; }
        public int ApplicationId { get; set; }
        public string PasswordResetToken { get; set; }
        public Nullable<System.DateTime> PasswordResetExpiration { get; set; }
        public Nullable<bool> IsLoggedIn { get; set; }
        public string Department { get; set; }
        public string Title { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public string MiddleInitial { get; set; }
        public string Suffix { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string IPAddress { get; set; }
        public Nullable<bool> AllowSingleSignOn { get; set; }
        public Nullable<bool> Deactivated { get; set; }
        public byte[] ReasonForDeactivation { get; set; }
        public Nullable<System.DateTime> DeactivationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Roles { get; set; }
    }
}
